/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedHospitalsIndexRouteImport } from './routes/_protected/hospitals/index'
import { Route as ProtectedHospitalsOrgIdIndexRouteImport } from './routes/_protected/hospitals/$orgId/index'
import { Route as ProtectedHospitalsOrgIdPrescriptionsPrescriptionIdRouteImport } from './routes/_protected/hospitals/$orgId/prescriptions/$prescriptionId'
import { Route as ProtectedHospitalsOrgIdBillsBillIdRouteImport } from './routes/_protected/hospitals/$orgId/bills/$billId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHospitalsIndexRoute = ProtectedHospitalsIndexRouteImport.update({
  id: '/hospitals/',
  path: '/hospitals/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHospitalsOrgIdIndexRoute =
  ProtectedHospitalsOrgIdIndexRouteImport.update({
    id: '/hospitals/$orgId/',
    path: '/hospitals/$orgId/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedHospitalsOrgIdPrescriptionsPrescriptionIdRoute =
  ProtectedHospitalsOrgIdPrescriptionsPrescriptionIdRouteImport.update({
    id: '/hospitals/$orgId/prescriptions/$prescriptionId',
    path: '/hospitals/$orgId/prescriptions/$prescriptionId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedHospitalsOrgIdBillsBillIdRoute =
  ProtectedHospitalsOrgIdBillsBillIdRouteImport.update({
    id: '/hospitals/$orgId/bills/$billId',
    path: '/hospitals/$orgId/bills/$billId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/hospitals/': typeof ProtectedHospitalsIndexRoute
  '/hospitals/$orgId/': typeof ProtectedHospitalsOrgIdIndexRoute
  '/hospitals/$orgId/bills/$billId': typeof ProtectedHospitalsOrgIdBillsBillIdRoute
  '/hospitals/$orgId/prescriptions/$prescriptionId': typeof ProtectedHospitalsOrgIdPrescriptionsPrescriptionIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof ProtectedIndexRoute
  '/hospitals': typeof ProtectedHospitalsIndexRoute
  '/hospitals/$orgId': typeof ProtectedHospitalsOrgIdIndexRoute
  '/hospitals/$orgId/bills/$billId': typeof ProtectedHospitalsOrgIdBillsBillIdRoute
  '/hospitals/$orgId/prescriptions/$prescriptionId': typeof ProtectedHospitalsOrgIdPrescriptionsPrescriptionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/hospitals/': typeof ProtectedHospitalsIndexRoute
  '/_protected/hospitals/$orgId/': typeof ProtectedHospitalsOrgIdIndexRoute
  '/_protected/hospitals/$orgId/bills/$billId': typeof ProtectedHospitalsOrgIdBillsBillIdRoute
  '/_protected/hospitals/$orgId/prescriptions/$prescriptionId': typeof ProtectedHospitalsOrgIdPrescriptionsPrescriptionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/hospitals/'
    | '/hospitals/$orgId/'
    | '/hospitals/$orgId/bills/$billId'
    | '/hospitals/$orgId/prescriptions/$prescriptionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/hospitals'
    | '/hospitals/$orgId'
    | '/hospitals/$orgId/bills/$billId'
    | '/hospitals/$orgId/prescriptions/$prescriptionId'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/'
    | '/_protected/hospitals/'
    | '/_protected/hospitals/$orgId/'
    | '/_protected/hospitals/$orgId/bills/$billId'
    | '/_protected/hospitals/$orgId/prescriptions/$prescriptionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/hospitals/': {
      id: '/_protected/hospitals/'
      path: '/hospitals'
      fullPath: '/hospitals/'
      preLoaderRoute: typeof ProtectedHospitalsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/hospitals/$orgId/': {
      id: '/_protected/hospitals/$orgId/'
      path: '/hospitals/$orgId'
      fullPath: '/hospitals/$orgId/'
      preLoaderRoute: typeof ProtectedHospitalsOrgIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/hospitals/$orgId/prescriptions/$prescriptionId': {
      id: '/_protected/hospitals/$orgId/prescriptions/$prescriptionId'
      path: '/hospitals/$orgId/prescriptions/$prescriptionId'
      fullPath: '/hospitals/$orgId/prescriptions/$prescriptionId'
      preLoaderRoute: typeof ProtectedHospitalsOrgIdPrescriptionsPrescriptionIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/hospitals/$orgId/bills/$billId': {
      id: '/_protected/hospitals/$orgId/bills/$billId'
      path: '/hospitals/$orgId/bills/$billId'
      fullPath: '/hospitals/$orgId/bills/$billId'
      preLoaderRoute: typeof ProtectedHospitalsOrgIdBillsBillIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedHospitalsIndexRoute: typeof ProtectedHospitalsIndexRoute
  ProtectedHospitalsOrgIdIndexRoute: typeof ProtectedHospitalsOrgIdIndexRoute
  ProtectedHospitalsOrgIdBillsBillIdRoute: typeof ProtectedHospitalsOrgIdBillsBillIdRoute
  ProtectedHospitalsOrgIdPrescriptionsPrescriptionIdRoute: typeof ProtectedHospitalsOrgIdPrescriptionsPrescriptionIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedHospitalsIndexRoute: ProtectedHospitalsIndexRoute,
  ProtectedHospitalsOrgIdIndexRoute: ProtectedHospitalsOrgIdIndexRoute,
  ProtectedHospitalsOrgIdBillsBillIdRoute:
    ProtectedHospitalsOrgIdBillsBillIdRoute,
  ProtectedHospitalsOrgIdPrescriptionsPrescriptionIdRoute:
    ProtectedHospitalsOrgIdPrescriptionsPrescriptionIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
